on: 
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  push:
  pull_request:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - name: Run tests
      run: bundle exec sus
    - name: gen hash
      run: |
        echo "hash=$(sha256sum accelerated-domains.china.conf)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v4
      with:
        name: ${{env.hash}}
        path: /dev/null
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: TG908/fork-sync@v1.6.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: felixonmars # fork 的上游仓库 user
          head: master # fork 的上游仓库 branch
          base: master # 本地仓库 branch
  Delete_workflow_runs:
    # 删除无用 workflow runs;
    runs-on: ubuntu-latest
    steps:
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0.1
        keep_minimum_runs: 1